language: node_js

node_js:
  - "0.10"

env: 
  - COVERAGE=true

script:
  - "make test"

branches:
  only:
    - master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/db9084078a6ceda4fe03
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
