# Site settings
title: Waterlock
author: "David Rivera"
email: david.r.rivera193@gmail.com
description: "Waterlock documentation"
baseurl: "http://waterlock.ninja"
url: "http://waterlock.ninja"

# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: :compress
  sass_dir: _sass